/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package qa.qcri.nadeef.service.thrift;


public enum TResultType implements org.apache.thrift.TEnum {
  OK(0),
  COMPILE_ERROR(1),
  INVALID_RULE(2);

  private final int value;

  private TResultType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static TResultType findByValue(int value) { 
    switch (value) {
      case 0:
        return OK;
      case 1:
        return COMPILE_ERROR;
      case 2:
        return INVALID_RULE;
      default:
        return null;
    }
  }
}
